[package]
name = "massa-sc-runtime"
version = "0.6.9"
edition = "2021"

[dependencies]
anyhow = "1.0"
lazy_static = "1"
serde = "1.0"
serde_json = "1.0"
wasmer = { version = "2.3.0", default-features = false, features = [ "std" ] }
as-ffi-bindings = "0.2.5"
wasmer-compiler-singlepass = { version = "2.3.0", default-features = false, features = [ "std" ] }
wasmer-engine-universal = { version = "2.3.0", default-features = false, features = [ ] }
wasmer-middlewares = { version = "2.3.0", default-features = false, features = [ ] }
cornetto = "0.1.0"
base64 = "0.13.0"
serial_test = "0.5.1"
loupe = "0.1.3"
