[package]
name = "massa-sc-runtime"
version = "0.6.6"
edition = "2021"

[dependencies]
anyhow = "1.0"
lazy_static = "1"
serde = "1.0"
serde_json = "1.0"
wasmer = "2.2.1"
as-ffi-bindings = "0.2.4"
wasmer-compiler-singlepass = { version = "2.2.1", default-features = false, features = [ "avx", "std" ] }
wasmer-engine-universal = "2.2.1"
wasmer-middlewares = "2.2.1"
cornetto = "0.1.0"
base64 = "0.13.0"
serial_test = "0.5.1"
loupe = "0.1.3"
